Repository puppetlabs/influxdb, pull requests merged in 2022-10, with the labels that each got.

#47 Change apt dependency to >= 8.0.0
  metadata.json
Labels: maintenance

#46 Helpful fail message for local host req on install
  manifests/init.pp
Labels: enhancement

#50 (SUP-3705) Require Apt::Update class on Ubuntu
  manifests/init.pp
Labels: bug
