Repository puppetlabs/influxdb, pull requests merged in 2023-02, with the labels that each got.

#61 Update influxdb repo key
  data/common.yaml
  spec/classes/init_spec.rb
Labels: bug

#64 Pin changelog version
  .sync.yml
Labels: maintenance

#65 (SUP-3968) Support paginated api responses
  lib/puppet/provider/influxdb_auth/influxdb_auth.rb
  lib/puppet/provider/influxdb_bucket/influxdb_bucket.rb
  lib/puppet/provider/influxdb_dbrp/influxdb_dbrp.rb
  lib/puppet/provider/influxdb_label/influxdb_label.rb
  lib/puppet/provider/influxdb_org/influxdb_org.rb
  lib/puppet/provider/influxdb_setup/influxdb_setup.rb
  lib/puppet/provider/influxdb_user/influxdb_user.rb
  lib/puppet_x/puppetlabs/influxdb/influxdb.rb
  spec/classes/init_spec.rb
  spec/unit/puppet/provider/influxdb_auth/influxdb_auth_spec.rb
  spec/unit/puppet/provider/influxdb_bucket/influxdb_bucket_spec.rb
  spec/unit/puppet/provider/influxdb_dbrp/influxdb_dbrp_spec.rb
  spec/unit/puppet/provider/influxdb_label/influxdb_label_spec.rb
  spec/unit/puppet/provider/influxdb_org/influxdb_org_spec.rb
  spec/unit/puppet/provider/influxdb_setup/influxdb_setup_spec.rb
  spec/unit/puppet/provider/influxdb_user/influxdb_user_spec.rb
Labels: bug

#67 PDK update
  .devcontainer/README.md
  .sync.yml
  Gemfile
  functions/hosts_with_pe_profile.pp
  manifests/init.pp
  manifests/profile/toml.pp
  metadata.json
Labels: maintenance

#71 Add default 90 day bucket retention
  lib/puppet/type/influxdb_bucket.rb
  manifests/init.pp
  manifests/profile/toml.pp
  spec/unit/puppet/provider/influxdb_bucket/influxdb_bucket_spec.rb
Labels: enhancement
