Repository puppetlabs/influxdb, pull requests merged in 2023-05, with the labels that each got.

#66 Provider updates
  lib/puppet/functions/influxdb/retrieve_token.rb
  lib/puppet/provider/influxdb_auth/influxdb_auth.rb
  lib/puppet/provider/influxdb_bucket/influxdb_bucket.rb
  lib/puppet/provider/influxdb_dbrp/influxdb_dbrp.rb
  lib/puppet/provider/influxdb_label/influxdb_label.rb
  lib/puppet/provider/influxdb_org/influxdb_org.rb
  lib/puppet/provider/influxdb_user/influxdb_user.rb
  lib/puppet/type/influxdb_auth.rb
  lib/puppet/type/influxdb_bucket.rb
  lib/puppet/type/influxdb_dbrp.rb
  lib/puppet/type/influxdb_label.rb
  lib/puppet/type/influxdb_org.rb
  lib/puppet/type/influxdb_user.rb
  lib/puppet_x/puppetlabs/influxdb/influxdb.rb
  manifests/init.pp
  metadata.json
  spec/unit/puppet/provider/influxdb_auth/influxdb_auth_spec.rb
Labels: enhancement

#83 Update node manager version in fixtures
  .fixtures.yml
Labels: maintenance

#84 (SUP-4274) Swapped legacy fact fqdn for networking.fqdn
  data/common.yaml
Labels: bug

#86 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: maintenance

#87 Update CODEOWNERS
  CODEOWNERS
Labels: maintenance

#88 Update legacy fqdn fact
  lib/puppet_x/puppetlabs/influxdb/influxdb.rb
Labels: bug
